### ISSUE TITLE
Frontmatter-markdown metadata value type

### ISSUE THREAD

**Issue by Alysha-94** [shuttle1987/gilbert-frontmatter-markdown#3]
The frontmatter-loader stores metadata values as a list of strings and can't be rendered in the templates the same way as the metadata values from the yaml loader, which are stored as any type.

Take for example this line in our default.html template, which takes the value found in `title` and inserts it into the title tag:
```
{% block title %}{{ this.title }}{% endblock %}
```
For any `.yaml` extension being rendered the output is `<title>Blog</title>` with the value in the tag, but for any `.md` extension the rendered output is empty `<title></title>`

I added some print lines to see the difference in metadata. In frontmatter_markdown.py:
```
class FrontmatterMarkdownPage(Page):
    extras: list = ['meta']

    @oneshot
    def content(self):
        extras = self.extras
        if not extras:
            extras = self.site.config.get('content_type', {}).get('MarkdownPage', [])
        md = markdown.Markdown(extensions=extras, output_format='html5')
        processed = md.convert(self.data)
        print('md meta: ', md.Meta)
        return processed
```
gilbert render
```
Rendering index.md ...
md meta:  {'title': ['Home'], 'in_menu': ['False']}
```

I realised this from the [python markdown docs](https://python-markdown.github.io/extensions/meta_data/#accessing-the-meta-data) 
> Note that the keys are all lowercase and the values consist of a list of strings where each item is one line for that key.

Where as in yaml.py:
```
def load_yaml(path: Path):
    with path.open() as fin:
        loader = yaml.Loader(fin)
        meta = loader.get_data()
        # PyYAML Reader greedily consumes chunks from the stream.
        # We must recover any un-consumed data, as well as what's left in the stream.
        if loader.buffer:
            data = loader.buffer[loader.pointer:-1]
        else:
            data = ''
        data += fin.read()
        print('yaml meta: ', meta)
    return data, meta
```
gilbert render
```
Found 17 content objects.
yaml meta:  {'title': 'Blog', 'template': 'blog.html'}`
```
In [PyYAML](https://pyyaml.org/wiki/PyYAMLDocumentation)
> PyYAML allows you to construct a Python object of any type.

**Comment by shuttle1987** [comment]
@Alysha-94 thank you for the especially detailed bug report, I'll try to fix this

**Comment by shuttle1987** [comment]
What I'm thinking might be possible is changing this so it changes a single item into that value type if the schema says it's a single value type and try to get it to raise a validation error if there's multiple values provided for something that expects to get only a single item.

Take for example this schema:
```page
from typing import List
class Page:
    title: str
    authors: List[str]
```

Then this should validate:
```markdown
tilte: "OK"
authors:
    - "Author1"
    - "Author2"
---
```

But this should fail:
```markdown
tilte:
    - "not good"
    - "Still not good"
authors:
    - "Author1"
    - "Author2"
---
```
